export const PLANS = {
  MONTHLY: {
    name: "1 Aylık",
    price: 49.99,
    duration: 30,
    quality: ["SD", "HD"],
    maxProfiles: 2,
    animatedProfile: false,
    earlyAccess: false,
    badge: false,
  },
  THREE_MONTHS: {
    name: "3 Aylık",
    price: 129.99,
    duration: 90,
    quality: ["SD", "HD", "FHD"],
    maxProfiles: 3,
    animatedProfile: false,
    earlyAccess: false,
    badge: false,
  },
  SIX_MONTHS: {
    name: "6 Aylık",
    price: 229.99,
    duration: 180,
    quality: ["SD", "HD", "FHD", "UHD"],
    maxProfiles: 4,
    animatedProfile: false,
    earlyAccess: false,
    badge: false,
  },
  YEARLY: {
    name: "12 Aylık",
    price: 399.99,
    duration: 365,
    quality: ["SD", "HD", "FHD", "UHD"],
    maxProfiles: 4,
    animatedProfile: false,
    earlyAccess: true,
    badge: false,
  },
  LIFETIME: {
    name: "Sonsuz",
    price: 999.99,
    duration: null,
    quality: ["SD", "HD", "FHD", "UHD"],
    maxProfiles: 4,
    animatedProfile: true,
    earlyAccess: true,
    badge: true,
  },
} as const;

export type PlanKey = keyof typeof PLANS;
